name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install toolchain
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --verbose --release --target wasm32-unknown-unknown 
    - name: bindgen
      run: wasm-bindgen ./target/wasm32-unknown-unknown/release/egui_example.wasm --out-dir docs
    - name: opt wasm
      run: wasm-opt docs/egui_example_bg.wasm -O2 --fast-math -o docs/egui_example_bg.wasm
    - name: cache
      uses: actions/cache@v2
      with:
       path: |
        ~/.cargo/registry
        ~/.cargo/git
        target
       key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }} 
