name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install target
      run: rustup target add wasm32-unknown-unknown
    - name: install wasm-bingen
      run: cargo install wasm-bindgen-cli
    - name: update wasm-bindgen
      run: cargo update -p wasm-bindgen
    - name: Build
      run: cargo build --package egui_example --verbose --release --target wasm32-unknown-unknown 
    - name: bindgen
      run: wasm-bindgen ./target/wasm32-unknown-unknown/release/egui_example.wasm --out-dir docs
    - name: cache
      uses: actions/cache@v2
      with:
       path: |
        ~/.cargo/bin/wasm-bindgen
        ~/.cargo/bin/wasm2es6js
        ~/.cargo/registry
        ~/.cargo/git
        target
       key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }} 
